#!/bin/bash

QKD_HOME=`pwd`/..

cd ${QKD_HOME}/qnl/qnl-qll-service
mvn -N io.takari:maven:wrapper
./mvnw clean install
git update-index --assume-unchanged mvnw
git update-index --assume-unchanged mvnw.cmd