#!/bin/bash

QKD_HOME=`pwd`/..

cd ${QKD_HOME}/kms/kms-service
export SITE_PROPERTIES=$HOME/.qkd/kms/site.properties
mvn -N io.takari:maven:wrapper
./mvnw clean install -DskipTests # [@rahul revisit]: remove this hack once you're done.
git update-index --assume-unchanged mvnw
git update-index --assume-unchanged mvnw.cmd
