#!/bin/bash

# We require some files to be present to run this script successfully.
# We're asserting that they are present so we can catch errors early.
requiredFiles=(
    config-service/target/config-service-0.0.1-SNAPSHOT.jar
    registration-service/target/registration-service-0.0.1-SNAPSHOT.jar
    auth-service/target/auth-service-0.0.1-SNAPSHOT.jar
    kms-service/target/kms-service-0.0.1-SNAPSHOT.jar
    kms-api-gateway/target/kms-api-gateway-0.0.1-SNAPSHOT.jar
    kms-qnl-service/.mvnw
    ../../qnl/key-routing-service/./mvnw
    ../../qll_sim/.mvnw
)

for filePath in ${requiredFiles[@]}; do
    if [ ! -f $filePath ]; then
        echo "File $filePath not found"
        exit 1
    fi
done

mkdir -p ~/qkd_logs
screen -Sdm config-svc java -jar config-service/target/config-service-0.0.1-SNAPSHOT.jar
echo "Starting KMS config service..."
sleep 10s

screen -Sdm reg-svc scripts/run-registration-service
echo "Starting KMS registration service..."
sleep 20s

screen -Sdm auth-svc java -jar auth-service/target/auth-service-0.0.1-SNAPSHOT.jar
echo "Starting KMS auth service..."
sleep 20s

export SITE_PROPERTIES=$HOME/.qkd/kms/site.properties

screen -Sdm kms-svc scripts/run-kms-service
echo "Starting KMS service..."
sleep 20s

screen -Sdm kms-gw java -jar kms-api-gateway/target/kms-api-gateway-0.0.1-SNAPSHOT.jar
echo "Starting KMS API Gateway..."
sleep 20s

cd kms-qnl-service
screen -Sdm kms-qnl-svc ./mvnw exec:java
echo "Starting KMS QNL service..."

cd ../../qnl/key-routing-service
screen -Sdm kms-routing-svc ./mvnw exec:java
echo "Starting KMS routing service..."

cd ../../qll_sim
screen -Sdm qll-sim MAVEN_OPTS="-Dconfig.file=$HOME/.qkd/qll-sim/qll-sim.conf" ./mvnw exec:java
echo "Starting QLL sim..."

echo "run...done"
